---
name: Auto Start CI

on:
  pull_request_target:
    types:
      - labeled

jobs:
  startCI:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'request-ci'
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install node-core-utils
        run: npm install -g node-core-utils

      - name: Set variables
        run: |
          echo "::set-env name=REPOSITORY::$(echo ${{ github.repository }} | cut -d/ -f2)"
          echo "::set-env name=OWNER::${{ github.repository_owner }}"

      - name: Setup node-core-utils
        run: |
          ncu-config set username ${{ secrets.JENKINS_USER }}
          ncu-config set token none
          ncu-config set jenkins_token ${{ secrets.JENKINS_TOKEN }}
          ncu-config set owner ${{ env.OWNER }}
          ncu-config set repo ${{ env.REPOSITORY }}

      - name: Start CI
        run: ./tools/actions/start-ci.sh ${{ secrets.GITHUB_TOKEN }} ${{ env.OWNER }} ${{ env.REPOSITORY }} ${{ github.event.number }}
